#pragma once

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstring>
#include <exception>
#include <filesystem>
#include <format>
#include <functional>
#include <iomanip>
#include <iostream>
#include <memory>
#include <numbers>
#include <print>
#include <random>
#include <sstream>
#include <stacktrace>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <vector>
